import graphics.circle as ci
import graphics.rect as re
import graphics.subgraphics.cuboid as cu
import graphics.subgraphics.sphere as sp
print("area of a circle:",ci.area(2))
print("peremeter of a circle:",ci.pere(2))
print("area of a rectangle:",re.area(2,3))
print("peremeter of a rectangle:",re.pere(2,3))
print("area of a cuboid:",cu.area(1,1,1))
print("peremeter of a cuboid:",cu.pere(1,1,1))
print("area of a sphere",sp.area(2))
print("peremeter of a sphere",sp.pere(2))